/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_bme_innolearn_hrm_HRMSignalProcessor */

#ifndef _Included_hu_bme_innolearn_hrm_HRMSignalProcessor
#define _Included_hu_bme_innolearn_hrm_HRMSignalProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_bme_innolearn_hrm_HRMSignalProcessor
 * Method:    nativeCalcPSD
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hu_bme_aut_adapted_framework_sensors_zephyr_HRMSignalProcessor_nativeCalcPSD
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
